#!/bin/bash
set -e

mkdir -p ~/var/{lock,log}
lock=newsbeuter-reload
log="$lock-$RANDOM".log
postpone -f -L ~/var/lock/elock-"$lock" \
  ~/bin/mail-exec ~/var/log/"$log" "newsbeuter" \
  newsbeuter -x reload &>/dev/null &
