#!/bin/bash
set -e

mkdir -p ~/var/spool/anacron
/usr/sbin/anacron -t <(

for dir1 in ~/etc/anacron.d/*; do
  i=$(basename "$dir1")
  for dir2 in "$dir1"/*; do
    j=$(basename "$dir2")
    for script in "$dir2"/*; do
      s=$(basename "$script")
      echo "$i $j $i-$j-$s $script"
    done
  done
done

) -S ~/var/spool/anacron
