#!/bin/bash
set -e

mkdir -p ~/var/spool/anacron
/usr/sbin/anacron -t <(

for dir1 in ~/etc/anacron.d/*; do
  i=$(basename "$dir1")
  for dir2 in "$dir1"/*; do
    j=$(basename "$dir2")
    for script in "$dir2"/*; do
      if [ -x "$script" ]; then
        s="$(basename "$script" | sed 's/ /-/g')"
        key="$i-$j-$s"
        sum="$(md5sum <<< "$key" | cut -f 1 -d ' ')"
        lock=anacron-"$sum"
        echo "$i $j $i-$j-$s postpone -f -l ~/var/lock/lock-\"$lock\" \"$script\""
      fi
    done
  done
done

) -S ~/var/spool/anacron
